appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: fxOwVreO2qSytotYuHZJ0jfSpmrRUCJ2Ql4ZCjZ4THhW4WblhCRsdqSprB2dlvCdoK2hwgJmSBvSw3SQfReHEGP4L9jLbFsTe7+zAgzLo66YZIptLCYkvTqgimz2bD+3vp7Be1cbZfGuxZDuGWSAvbfE5hJ9bWEfPPqcCkIKqScLacGwBCZ2XaMKx02P2IgYu28PC/0qHkTV6YYe4BJn6jH4meJx+GYRzE5msE4nV0KomRbjqlpFxAlfUSzMX6MkSaUayxLF06RohA6r5MhnKACPUj9bs9uLNm22tQHe1hYcVtPNxhosi2WyabpZfM3a87BhBSK2vpTPfyEpYHi9Yv399k6BT3eBo0FftYTnHzEI2cw475uo50ZAIsgv7KkwEY9ap+siEsNcO+9L06/nCgAP9bgPiBcoawMnmsN+Mzhic2/z8pK0sgTlynu9MusKU5jDej6LxjYdsfct+r5P/AyHVYP0R9/tBfM+/eYw0F0qEo0kUu/ySX5+fLVQ/tMxakV+MrXpRgz741sKqDR5FP+xChQDGU68J59kW3z0axZK5QZYXmMivzzRqN5VYD0L13VTXwqZqmpKamIupIZNPNs/JlnnGsX2HAx+kpAIKXJzn1E94C2kiyYmF8jlJCVsEhwve1C3TOUjPvzX1xgGkafnG853fgmzjWoDk1BJIW4=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: false
